#!/usr/bin/env python3
"""Generate docs/outcomes.md from committed resolved prediction records."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = REPO_ROOT / "backend" / "app" / "data" / "resolved_predictions.json"
OUT_PATH = REPO_ROOT / "docs" / "outcomes.md"


def load_records() -> list[dict]:
    payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    records = payload.get("records", [])
    if not records:
        raise ValueError(f"No prediction records found in {DATA_PATH}")
    return records


def compute_metrics(records: list[dict]) -> dict[str, float | int]:
    resolved = [row for row in records if row.get("resolved")]
    abstained = [row for row in records if row.get("action") == "skip" or not row.get("resolved")]
    if not resolved:
        raise ValueError("Need at least one resolved prediction to compute outcome metrics")

    briers = [float(row["brier_component"]) for row in resolved]
    hits = sum(1 for row in resolved if row.get("hit_boolean"))
    return {
        "total_predictions": len(records),
        "resolved_predictions": len(resolved),
        "abstained_predictions": len(abstained),
        "abstain_rate": len(abstained) / len(records),
        "mean_brier": sum(briers) / len(briers),
        "hit_rate": hits / len(resolved),
    }


def render_markdown(metrics: dict[str, float | int]) -> str:
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return f"""# Chronos outcome metrics

Generated by [`scripts/generate_outcomes_doc.py`](../scripts/generate_outcomes_doc.py) from
[`backend/app/data/resolved_predictions.json`](../backend/app/data/resolved_predictions.json).

Last generated: {generated_at}

## Summary

| Metric | Value |
|--------|------:|
| Resolved predictions (n) | {metrics["resolved_predictions"]} |
| Mean Brier score | {metrics["mean_brier"]:.4f} |
| Resolution accuracy | {metrics["hit_rate"]:.1%} |
| Skip/abstain rate | {metrics["abstain_rate"]:.1%} |
| Total pipeline decisions | {metrics["total_predictions"]} |
| Abstained (skip) decisions | {metrics["abstained_predictions"]} |

## Notes

- **Brier score** averages `(calibrated_p - outcome)^2` over resolved predictions only.
- **Skip/abstain rate** is the share of pipeline decisions that did not promote a lead
  (`action=skip`), including confidence/EV guards and daily-cap displacement.
- Records are point-in-time resolver exports on the mock price track; they measure
  calibration quality, not trading P&L.
"""


def main() -> None:
    records = load_records()
    metrics = compute_metrics(records)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render_markdown(metrics), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
